###

GET http://localhost:4000/api/students

###

POST http://localhost:4000/api/students
Content-Type: application/json


{
    "ad": "caner",
    "soyad": "caymaz",
    "telefon": "455454",
    "email": "turancaymaz@hotmail",
    "hakkinda": "dddddd"

}

###
GET http://localhost:4000/api/students/60281ad60d56b33708392133

###
DELETE http://localhost:4000/api/students/602819eed43a122b6833d687

###
PUT http://localhost:4000/api/students/60281ad60d56b33708392133
Content-Type: application/json

{
    "soyad": "cann"

}


